# Generated by Django 2.1.2 on 2018-10-29 17:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181029_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 17, 26, 43, 892093, tzinfo=utc)),
        ),
    ]
