# Generated by Django 2.1.2 on 2018-10-29 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181029_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 18, 16, 35, 166407, tzinfo=utc)),
        ),
    ]
