# Generated by Django 2.1.2 on 2018-10-30 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20181030_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 10, 23, 59, 271473, tzinfo=utc)),
        ),
    ]
